### ISSUE TITLE
Unable to locate a running instance of steam

### ISSUE THREAD

**Issue by danpolanco** [TuRz4m/Project-Zomboid_Docker#1]
On clean install I'm getting this error.

[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
Message: 'Fatal Error', Detail: 'Steam must be running to play this game (SteamAPI_Init() failed).

**Comment by danpolanco** [comment]
Perhaps this?

https://developer.valvesoftware.com/wiki/SteamCMD#Unable_to_locate_a_running_instance_of_Steam

**Comment by TuRz4m** [comment]
Since the dedicated server was moved to another repository, I think you were trying to launch the Project zomboid game inside the docker. I could be wrong, but can you test with the new version of the image ?

**Comment by danpolanco** [comment]
Yup I can! It's going through setup right now.

**Comment by danpolanco** [comment]
Jeez. Thank you so much. I was banging my head on the wall trying to figure out what was wrong. It looks like it started up just fine.

Thank you again. :dancer:
