### ISSUE TITLE
Rename shell script?

### ISSUE THREAD

**Issue by danpolanco** [TuRz4m/Project-Zomboid_Docker#2]
I'm also getting this error on a clean install.

/home/steam/update.sh: line 14: /home/steam/projectzomboid/projectzomboid-dedi-server.sh: No such file or directory

**Comment by danpolanco** [comment]
When I `cp projectzomboid.sh projectzomboid-dedi-server.sh`, it works.

**Comment by TuRz4m** [comment]
PZ has a new dedicated server app on steam (https://steamdb.info/app/380870/) and this docker image was not updated.
Now it should work fine !

**Comment by danpolanco** [comment]
Yup. Good to go!
